SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `ZtaUzt14` ;
CREATE SCHEMA IF NOT EXISTS `ZtaUzt14` DEFAULT CHARACTER SET latin1 ;
USE `ZtaUzt14` ;

GRANT ALL PRIVILEGES ON ZtaUzt14.* TO 'ikasle'@'localhost' IDENTIFIED BY 'zta';

USE `ZtaUzt14` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
